src/Entity/Panier.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PanierRepository")
 */
class Panier
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="paniers")
     */
    private $user;

    /**
     * @ORM\Column(type="datetime",nullable=true)
     */
    private $bought_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $state = false;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ContenuPanier", mappedBy="panier", orphanRemoval=true)
     */
    private $contenuPaniers;

    public function __construct()
    {
        $this->contenuPaniers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getBoughtAt(): ?\DateTimeInterface
    {
        return $this->bought_at;
    }

    public function setBoughtAt(\DateTimeInterface $bought_at): self
    {
        $this->bought_at = $bought_at;

        return $this;
    }

    public function getState(): ?bool
    {
        return $this->state;
    }

    public function setState(bool $state): self
    {
        $this->state = $state;

        return $this;
    }

    /**
     * @return Collection|ContenuPanier[]
     */
    public function getContenuPaniers(): Collection
    {
        return $this->contenuPaniers;
    }

    public function addContenuPanier(ContenuPanier $contenuPanier): self
    {
        if (!$this->contenuPaniers->contains($contenuPanier)) {
            $this->contenuPaniers[] = $contenuPanier;
            $contenuPanier->setPanier($this);
        }

        return $this;
    }

    public function removeContenuPanier(ContenuPanier $contenuPanier): self
    {
        if ($this->contenuPaniers->contains($contenuPanier)) {
            $this->contenuPaniers->removeElement($contenuPanier);
            // set the owning side to null (unless already changed)
            if ($contenuPanier->getPanier() === $this) {
                $contenuPanier->setPanier(null);
            }
        }

        return $this;
    }
}

src/Form/PanierType.php
<?php

namespace App\Form;

use App\Entity\Panier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PanierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('contenuPanier')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Panier::class,
        ]);
    }
}

src/Controller/PanierController.php
<?php

namespace App\Controller;

use App\Entity\Panier;
use App\Entity\ContenuPanier;
use App\Form\PanierType;
use App\Repository\PanierRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/{_locale}/panier")
 */
class PanierController extends AbstractController
{
    /**
     * @Route("/", name="panier_index", methods={"GET"})
     */
    public function index(PanierRepository $panierRepository): Response
    {
        return $this->render('panier/index.html.twig', [
            'paniers' => $panierRepository->findOneBy(['user'=> $this->getUser(), 'state'=> false]),
        ]);
    }

    /**
     * @Route("/new", name="panier_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $panier = new Panier();
        $form = $this->createForm(PanierType::class, $panier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($panier);
            $entityManager->flush();

            return $this->redirectToRoute('panier_index');
        }

        return $this->render('panier/new.html.twig', [
            'panier' => $panier,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="panier_show", methods={"GET"})
     */
    public function show(Panier $panier, Request $request, $id): Response
    {
        $em = $this->getDoctrine()->getManager();
        $articles = $em->getRepository(ContenuPanier::class)->findBy($id);
        return $this->render('panier/show.html.twig', [
            'panier' => $panier,
            'articles' => $articles
        ]);
    }

    /**
     * @Route("/{id}/edit", name="panier_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Panier $panier): Response
    {
        $form = $this->createForm(PanierType::class, $panier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('panier_index');
        }

        return $this->render('panier/edit.html.twig', [
            'panier' => $panier,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="panier_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Panier $panier): Response
    {
        if ($this->isCsrfTokenValid('delete'.$panier->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($panier);
            $entityManager->flush();
        }

        return $this->redirectToRoute('panier_index');
    }
}

templates/panier/_delete_form.html.twig
<form method="post" action="{{ path('panier_delete', {'id': panier.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ panier.id) }}">
    <button class="btn">Delete</button>
</form>

templates/panier/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/panier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Panier{% endblock %}

{% block body %}
    <h1>Edit Panier</h1>

    {{ include('panier/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('panier_index') }}">back to list</a>

    {{ include('panier/_delete_form.html.twig') }}
{% endblock %}

templates/panier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier index{% endblock %}

{% block body %}
    <h1>Panier index</h1>

    <table class="table">
        <thead>
            <tr>
                <td>{{'table.product'|trans}}</td>
                <td>{{'table.quantity'|trans}}</td>
                <td>{{'table.price'|trans}}</td>
                <td>{{'table.amount'|trans}}</td>
                <td>{{'table.action'|trans}}</td>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>

        {% set total = 0 %}
        {% set totalProduit = 0 %}
        {% for contenu in paniers.contenuPaniers %}
            

                {% set totalProduit = contenu.quantity * contenu.produit.price %}
                {% set total = total + totalProduit %}
        
                <tr>
                    <td>{{contenu.produit.name}}</td>
                    <td>{{contenu.quantity}}</td>
                    <td>{{contenu.produit.price}} $</td>
                    <td>{{contenu.quantity}}</td>
                    <td>{{totalProduit}} $</td>
                    <td><a href="{{path('contenu_panier_delete', {id:contenu.id})}}" class="btn btn-danger">{{'Delete'|trans}}</a></td>

                </tr>
            {% endfor %}
                    <a href="{{ path('panier_show', {'id': paniers.id}) }}">show</a>
                    <a href="{{ path('panier_edit', {'id': paniers.id}) }}">edit</a>
                </td>
            </tr>

        </tbody>
    </table>

    <a href="{{ path('panier_new') }}">Create new</a>
{% endblock %}

templates/panier/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Panier{% endblock %}

{% block body %}
    <h1>Create new Panier</h1>

    {{ include('panier/_form.html.twig') }}

    <a href="{{ path('panier_index') }}">back to list</a>
{% endblock %}

templates/panier/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{'panier.title'|trans}}{% endblock %}

{% block body %}
    <h1>{{'panier.title'|trans}}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ panier.id }}</td>
            </tr>
            <tr>
                <th>{{'panier.date'|trans}}</th>
                <td>{{ panier.boughtAt ? panier.boughtAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>State</th>
                {% if panier.state is same as(true) %}
                    <td><i class="fas fa-check"></i></td>
                {% else %}
                    <td><i class="fas fa-times"></i> }}</td>
                {% endif %}
            </tr>
        </tbody>
    </table>

    <a href="{{ path('panier_index') }}">back to list</a>

    <a href="{{ path('panier_edit', {'id': panier.id}) }}">edit</a>

    {{ include('panier/_delete_form.html.twig') }}
{% endblock %}