src/Entity/ContenuPanier.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ContenuPanierRepository")
 */
class ContenuPanier
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Produit", inversedBy="contenuPaniers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $produit;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Panier", inversedBy="contenuPaniers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $panier;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\Column(type="datetime")
     */
    private $added_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): self
    {
        $this->produit = $produit;

        return $this;
    }

    public function getPanier(): ?Panier
    {
        return $this->panier;
    }

    public function setPanier(?Panier $panier): self
    {
        $this->panier = $panier;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getAddedAt(): ?\DateTimeInterface
    {
        return $this->added_at;
    }

    public function setAddedAt(\DateTimeInterface $added_at): self
    {
        $this->added_at = $added_at;

        return $this;
    }
}

src/Form/ContenuPanierType.php
<?php

namespace App\Form;

use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use App\Entity\ContenuPanier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContenuPanierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('quantity')
            ->add('Add-cart', SubmitType::class);
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ContenuPanier::class,
        ]);
    }
}

src/Controller/ContenuPanierController.php
<?php

namespace App\Controller;

use App\Entity\ContenuPanier;
use App\Form\ContenuPanierType;
use App\Repository\ContenuPanierRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/{_locale}/contenu/panier")
 */
class ContenuPanierController extends AbstractController
{
    /**
     * @Route("/", name="contenu_panier_index", methods={"GET"})
     */
    public function index(ContenuPanierRepository $contenuPanierRepository): Response
    {
        return $this->render('contenu_panier/index.html.twig', [
            'contenu_paniers' => $contenuPanierRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="contenu_panier_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $contenuPanier = new ContenuPanier();
        $form = $this->createForm(ContenuPanierType::class, $contenuPanier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($contenuPanier);
            $entityManager->flush();

            return $this->redirectToRoute('contenu_panier_index');
        }

        return $this->render('contenu_panier/new.html.twig', [
            'contenu_panier' => $contenuPanier,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="contenu_panier_show", methods={"GET"})
     */
    public function show(ContenuPanier $contenuPanier): Response
    {
        return $this->render('contenu_panier/show.html.twig', [
            'contenu_panier' => $contenuPanier,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="contenu_panier_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, ContenuPanier $contenuPanier): Response
    {
        $form = $this->createForm(ContenuPanierType::class, $contenuPanier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('contenu_panier_index');
        }

        return $this->render('contenu_panier/edit.html.twig', [
            'contenu_panier' => $contenuPanier,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="contenu_panier_delete", methods={"DELETE"})
     */
    public function delete(Request $request, ContenuPanier $contenuPanier): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contenuPanier->getId(), $request->request->get('_token'))) {
            try{
              $entityManager = $this->getDoctrine()->getManager();
              $entityManager->remove($contenuPanier);
              $entityManager->flush();
            }catch(\Exception $e){
                error_log($e->getMessage());
            }
        }

        return $this->redirectToRoute('contenu_panier_index');
    }
}

templates/contenu_panier/_delete_form.html.twig
<form method="post" action="{{ path('contenu_panier_delete', {'id': contenu_panier.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contenu_panier.id) }}">
    <button class="btn">Delete</button>
</form>

templates/contenu_panier/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/contenu_panier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ContenuPanier{% endblock %}

{% block body %}
    <h1>Edit ContenuPanier</h1>

    {{ include('contenu_panier/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('contenu_panier_index') }}">back to list</a>

    {{ include('contenu_panier/_delete_form.html.twig') }}
{% endblock %}

templates/contenu_panier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ContenuPanier index{% endblock %}

{% block body %}
    <h1>ContenuPanier index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Quantity</th>
                <th>Added_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for contenu_panier in contenu_paniers %}
            <tr>
                <td>{{ contenu_panier.id }}</td>
                <td>{{ contenu_panier.quantity }}</td>
                <td>{{ contenu_panier.addedAt ? contenu_panier.addedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('contenu_panier_show', {'id': contenu_panier.id}) }}">show</a>
                    <a href="{{ path('contenu_panier_edit', {'id': contenu_panier.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('contenu_panier_new') }}">Create new</a>
{% endblock %}

templates/contenu_panier/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ContenuPanier{% endblock %}

{% block body %}
    <h1>Create new ContenuPanier</h1>

    {{ include('contenu_panier/_form.html.twig') }}

    <a href="{{ path('contenu_panier_index') }}">back to list</a>
{% endblock %}

templates/contenu_panier/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ContenuPanier{% endblock %}

{% block body %}
    <h1>ContenuPanier</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ contenu_panier.id }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ contenu_panier.quantity }}</td>
            </tr>
            <tr>
                <th>Added_at</th>
                <td>{{ contenu_panier.addedAt ? contenu_panier.addedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('contenu_panier_index') }}">back to list</a>

    <a href="{{ path('contenu_panier_edit', {'id': contenu_panier.id}) }}">edit</a>

    {{ include('contenu_panier/_delete_form.html.twig') }}
{% endblock %}